### ISSUE TITLE
Judgment Range of First Link Note 锁链头的判定范围

### ISSUE THREAD

**Issue by yao981113** [TigerHix/Cytoid#15]
Currently the range is too big: clicking the center of a note will trigger a black Perfect of the head of a link 1/4 of a screen later. (Example: Togen Renka chart by yyao)

**Comment by TigerHix** [comment]
这个有点难办啊，我下个版本调小一点，看看合不合适吧（主要希望锁链不会太难拉

**Comment by yao981113** [comment]
如果我没记错的话锁链的判定范围就是note本身，做个参考吧。（目前锁链糊起来似乎的确有些太顺畅了...）

**Comment by TigerHix** [comment]
已调整锁链判定范围（1.3x -> 1.15x）。

**Comment by yao981113** [comment]
好像锁链大小作了调整之后爆头的问题又多起来了……

**Comment by TigerHix** [comment]
@yao981113 痛心... 而另一边有人抱怨手机上锁链太难拉

到底是要怎样（抓狂）

**Comment by yao981113** [comment]
啊锁链头而已啦，锁链本身没问题的。
