### ISSUE TITLE
Number of decimal places for TP/Accuracy percentage

### ISSUE THREAD

**Issue by yao981113** [TigerHix/Cytoid#26]
By Cytus convention, there should always be two decimal places unless it's TP100, even if they are zeroes.

**Comment by TigerHix** [comment]
我是觉得整数显示起来很有美感才特意这么弄的2333

要是不合适的话我还是改回小数点后两位吧

**Comment by yao981113** [comment]
目前看起来的话就连98.0032...%这样也会显示成98%，就有点误导人。而且打歌的时候Accuracy那一行的长度一直在变感觉不太美观。
