### ISSUE TITLE
Difficult to understand how to play as a player!

### ISSUE THREAD

**Issue by natsupy** [TigerHix/Cytoid#27]
The intro looks awesome, but like a title, I downloaded the game on google play, after opening it, as a player I don't clear how to play and add the song to the game. When click Go, data is null and can't play!

**Comment by TigerHix** [comment]
I'm sorry for the unclear instructions T.T

You just need to go to https://cytoid.io/browse and you can download new levels there! (There are 100+ levels there now) Also refer to the wiki if you want to create your own levels. Cheers!

**Comment by TigerHix** [comment]
By the way what do you mean by "data is null"?

**Comment by natsupy** [comment]
Uhm, I tried to download it while playing but nothing happened, will the files auto-sync with the game or need to access it like Osu on PC, the lunar console warning them "data is null" when I click Go();
Do you have a version for PC? Can you upload it on https://itch.io/? It'll be awesome, btw on there will have a music game jam :">
![image](https://user-images.githubusercontent.com/15712687/29712523-6f801884-89c4-11e7-8950-3aff8d9b0431.png)
![image](https://user-images.githubusercontent.com/15712687/29712538-8688006e-89c4-11e7-944d-08bdd112c889.png)

**Comment by TigerHix** [comment]
This is very weird, I will check it out when I'm home. Meanwhile, could you
try download this level (https://cytoid.io/browse/yy.haelequin) and open
it? You should see that you can open the .cytoidlevel file with Cytoid.
Open it with Cytoid and restart the game and you will see the level
appears. Try playing this level and see if there are anymore errors,
because there do exist some problems with the built in "Glow Dance" level.

And thanks for the invitation! But this game is for phones (multi-touch).
It is actually a replica of a rhythm game called Cytus, so I dont know if I
should upload it to itch.io XD

**Comment by natsupy** [comment]
![image](https://user-images.githubusercontent.com/15712687/29713645-cf3160bc-89c9-11e7-920b-2ed09978ed17.png)
Wating for you, I open it with another root browser, and have this error, can you made a file browser in game to easily open files downloaded in your game
can refer this repo
http://unitylist.com/r/8b4/unity-simple-file-browser

**Comment by TigerHix** [comment]
All level files are located under /mnt/sdcard/Cytoid folder. Try deleting
the whole folder maybe?

I really wish to add a file browser but I am running out of time recently
(;_;)

**Comment by TigerHix** [comment]
I tried a fresh install on an Android device and couldnt replicate the
error you were having. Have you installed any levels?

**Comment by natsupy** [comment]
Uhm, I open the files downloaded from your site, then your app opening and show that error.
While opening app stand alone, the screen show like that T.T
![image](https://user-images.githubusercontent.com/15712687/29720159-3a8a21f0-89e3-11e7-93af-d60791486c9d.png)

**Comment by TigerHix** [comment]
That is so strange. Could you deleting "Cytoid" folder in your sdcard, and
try reinstalling the game?

I'm so sorry for your inconvenience ;/

**Comment by natsupy** [comment]
![image](https://user-images.githubusercontent.com/15712687/29723249-08f058fc-89ee-11e7-96a6-88253b23c117.png)
![image](https://user-images.githubusercontent.com/15712687/29723260-17d3603a-89ee-11e7-895b-ec2009daf691.png)
I uninstall and reinstall, and wait for the importing 5 minutes ago and still importing like that :v

**Comment by TigerHix** [comment]
This is so strange... Could you please press on that error ("ArgumentNullException: Argument cannot be null \n Parameter name: bytes") and screenshot the error stacktrace for me? Thanks a lot!

**Comment by natsupy** [comment]
![image](https://user-images.githubusercontent.com/15712687/29727496-5ce2a496-89fe-11e7-80bb-f64860b53d75.png)
I don't understand but now can open it :v

**Comment by TigerHix** [comment]
Please download and install this hotfix here and see if it works for you.
https://www.dropbox.com/s/hr4bvhjk0vbazw3/1.2.2_hotfix.apk?dl=0

Meanwhile, did you allow Cytoid to read/write your sdcard?

**Comment by natsupy** [comment]
Yup, when installing from google play, I have to allow it. Yeah, new update can be playing, except the warning check box Dev Build, great work!

![image](https://user-images.githubusercontent.com/15712687/29729097-ef4611e6-8a04-11e7-9c91-f78726d13090.png)

**Comment by TigerHix** [comment]
Glad it finally worked! I will investigate into this issue. Please feel free to browse the user levels -
 there is quite a lot right now ;)

Also, don't forget to adjust "Chart offset" in Options if you feel the notes are out of sync.

**Comment by natsupy** [comment]
Thank you, that'll help to reference how to make the asset can run outside like that.

**Comment by TigerHix** [comment]
Haha, Unity sucks very much when it comes to loading external assets. It is super stupid. Even now audio won't be streamed correctly in Cytoid!

**Comment by natsupy** [comment]
Uhm, I not enough good to say some thing stupid T.T But about streaming audio, can you try with this free trial asset, it focus on streaming video, but in this game, we just need streaming audio, can using it with this free version ;D
http://renderheads.com/product/avpro-video/

**Comment by TigerHix** [comment]
This seems really good! Unfortunately I have to make Cytoid more... open-source, I'm now trying hard to prevent using external assets that cannot be covered under MIT license. I would do check it out! Thanks so much <3

**Comment by natsupy** [comment]
Wow, That’s really nice, keep it up, 5ting! ^ ^
