### ISSUE TITLE
Manage levels in game 游戏内管理关卡

### ISSUE THREAD

**Issue by TigerHix** [TigerHix/Cytoid#29]

**Comment by gfsd20433** [comment]
加個刪譜功能吧 
重複下載的刪不掉 就留在這裏 orz

**Comment by TigerHix** [comment]
@gfsd20433 Android 可以直接用文件管理查看 sdcard 根目錄下的 Cytoid 目錄
iOS 的話連接 iTunes -> Apps -> File Sharing -> Cytoid 也可以達到一樣的功能

遊戲內的話還是等我有空一點再說 orz
