### ISSUE TITLE
Revamp in-game UI

### ISSUE THREAD

**Issue by TigerHix** [TigerHix/Cytoid#34]
![image](https://user-images.githubusercontent.com/3406505/29741950-16ab62d2-8aa9-11e7-9b13-256f59e90a78.png)

![image](https://user-images.githubusercontent.com/3406505/29741973-6965b5f4-8aa9-11e7-9207-6e77eb57197b.png)
![image](https://user-images.githubusercontent.com/3406505/29741974-6ab32e14-8aa9-11e7-85a0-f858b78d7735.png)

- [ ] Rhombus-shaped highlight
- [ ] Wider hold rail
- [x] Larger chain notes (1.5x?)
- [ ] #38

**Comment by gfsd20433** [comment]
日後會加slider球嗎?
