### ISSUE TITLE
about scanline

### ISSUE THREAD

**Issue by gfsd20433** [TigerHix/Cytoid#37]
I think it is necessary to set the start location of scan-line back to the bottom because Cytunity is also starting at the bottom (When page-shift is 0). Charters sometimes consider with the start location while making their chart. It is obviously effected when charting word-pattern or shape-pattern. Although there is a mod "inverse" for transferring the chart, it is not a default choice, or saying "using mod for no mod" is a bit weird. And now some players have already upload their upside-down play on youtube. I think they don't know they have played in actual inverse. So I hope you can make change of it. 

On the other hand, I hope the scan-line can be thicker, just a personal thought.

**Comment by TigerHix** [comment]
因為大大似乎是國人那我就用中文回覆吧 233

這個問題我至今沒有搞明白，到底 Cytunity 作出來的譜子，導進 Cytus 本體的話是不是反的？因為我拿 Cytus 的譜面導入 Cytoid，是不需要開啟 Inverse 選項且沒有反轉的問題的。所以我一直懷疑是制譜工具導出的譜子本身就是反的。由於我是 Mac 無法裝 Cytunity，還望大大幫忙確認一下。

我的想法是，假如確認了 Cytunity、PCytus 等制譜工具的譜子導出後都會反轉，那麼我就將 Inverse 設置為默認開啟吧。

**Comment by TigerHix** [comment]
Fixed in 1.4.
