### ISSUE TITLE
Song selection interface scrolling effect improvment 卷页效果改进

### ISSUE THREAD

**Issue by PretTy-Fish** [TigerHix/Cytoid#38]
Doesn't bounce back very fast when hit the top or the bottom.
回弹速度不够快

Suggestion:
建议：
1. Elastic top & bottom (like scrolling down a list in iOS)
弹性的顶和底（像苹果里卷页效果一样）
2. Stop when scrolling over a certain distance (like scrolling down a list in Android or in Deemo)
移动出列表后一小段距离停下（像安卓/Deemo里那样）

Also doesn't let the finger to react with the position where there is no text on the same line (same as outside of the list), which make it less handy.
以及同一行里没有字的话无法用手指拖动去翻页（也就是列表之外），使翻页不便
（（（

**Comment by TigerHix** [comment]
预计 2.0 完全改革选曲 UI。
