### ISSUE TITLE
cytoid IOS

### ISSUE THREAD

**Issue by fdo95** [TigerHix/Cytoid#39]
hi , glad to know this awesome simulator
 already played for 2 days , but i hope cytoid can edit for song folder ( so we dont need to use itunes , or uninstall the apps to make a new song list)

good job dev

**Comment by TigerHix** [comment]
Sure thing! It is already on the works. :)

**Comment by TigerHix** [comment]
By the way would you press that button on the upper right corner for me?
![image](https://user-images.githubusercontent.com/3406505/29787259-e2f8db7c-8c60-11e7-9d8b-7c12e1f241d2.png)

😂😂😂 Anyway, thanks for the suggestion. Lots of people are requesting that!

**Comment by fdo95** [comment]
sure , thank you dev <3
