### ISSUE TITLE
accidentcially clicked Pause

### ISSUE THREAD

**Issue by fdo95** [TigerHix/Cytoid#40]
the title say it all , (when playing)

**Comment by gfsd20433** [comment]
pause button is at the top right corner (last digit of the score)

**Comment by natsupy** [comment]
or @TigerHix  can add pause button by hard key Back on a device Android, or ios device(don't use it but I think it had) this's simple I used in my game
https://gist.github.com/natsupy/e6a7f8a949c21aaf321d6960e4a48212

**Comment by TigerHix** [comment]
Decreases the pause hitbox and added back button.
