### ISSUE TITLE
Featured charts / Ranking criteria

### ISSUE THREAD

**Issue by gfsd20433** [TigerHix/Cytoid#42]
just ask.

you haven't explain about it in FAQ  (´～`)

**Comment by TigerHix** [comment]
這個會盡快補上 (´～`)(´～`) 主要用英文寫比較費勁（#

The criteria will be online shortly.

**Comment by TigerHix** [comment]
我們正在緩慢推審譜進度，會先從比較前的頁數開始。我個人是很喜歡你的譜面啦（///

**Comment by gfsd20433** [comment]
我覺得可以譜面rank前都公開討論下之類的 030

**Comment by TigerHix** [comment]
等以後我時間充裕了應該會將網站重新構架一遍，加入由社區驅動的 Ranking 機制。現在由於人手嚴重不足 + 難以挖掘良譜 唯有由我們內部先自行評核啦~ 囧

**Comment by gfsd20433** [comment]
好吧 我想現在還是急需補充些featured譜 你們加油 :3/

**Comment by gfsd20433** [comment]
突然想起你們可以加果提交系統 真的想要rank的才審核 可以加速審核時間
現在想想我有些譜不太適合rank 就不用花時間在那些譜了 :3
