### ISSUE TITLE
Help with uploading

### ISSUE THREAD

**Issue by Luigi9990** [TigerHix/Cytoid#44]
Hi there, I made a level that I'm trying to upload and I'm having problems with the level.json. I copied the format that was in the wiki  (here is my file: https://gyazo.com/08be8c514f0b24b96addb077fed91c19). In notepad i saved it as a .json with the UTF-8 encoding.

However, when I try to upload it to the cytoid db, I get this error. https://gyazo.com/572199407dbf4a1e0a348904437db94b

And here is my zip file (I kept everything as default names to simplify it) https://gyazo.com/7a49588544151ce3594c6197f8e1be92

I'm not sure what I'm doing wrong, if I could have some help that'd be great. Thank you

**Comment by TigerHix** [comment]
Hello, could you upload the whole zip file here so I can see what's wrong with the files? :)

It seems like the level.json is not in correct encoding. Notepad does a very bad job at encoding stuff, I recommend you to use Notepad++ or Sublime Text when editing text files.

**Comment by Luigi9990** [comment]
I tried using Notepad++ and it worked, didn't realize notepad was stupid to make a json in. Thanks for your suggestion!
