### ISSUE TITLE
Improve search type level after downloaded beatmap

### ISSUE THREAD

**Issue by natsupy** [TigerHix/Cytoid#47]
I just create the simple search type to improve after downloaded a beatmap, it seems works ok when I testing on my device, can you try this
https://gist.github.com/natsupy/43ceb91938e22a7cb9f1eeee1035f0f4

**Comment by TigerHix** [comment]
This seems really useful!! Thanks for the effort :]

Right now I'm being busy with studying so I would work on Cytoid after a while. But thanks so much for the contribution you've made for the game 🙇🙇🙇

**Comment by natsupy** [comment]
I hope that'll help ^^
