### ISSUE TITLE
Cytoid won't build due to compiler errors

### ISSUE THREAD

**Issue by Ark12917** [TigerHix/Cytoid#58]
<img width="1020" alt="cytoid errors" src="https://user-images.githubusercontent.com/26558615/32135204-b13e27f2-bc2d-11e7-8af9-e679435f472c.PNG">
Even with all the paid assets imported... any idea why?

**Comment by TigerHix** [comment]
The list of used assets wasn't complete. As you can see ZPlayerPrefs and ANAMusic are missing.

Will update the list.

**Comment by Ark12917** [comment]
Yeah uhh thanks. I figured it out a long time ago (I was new to unity back then.) Anyway it's a good thing you're updating the list so other people don't get confused.
