### ISSUE TITLE
(Android)Cytoid 直接导入问题

### ISSUE THREAD

**Issue by ZeroAurora** [TigerHix/Cytoid#65]
单击.cytoidlevel 文件，打开后未导入。
SD卡目录新增 `Cytoid[曲包名].cytoidlevel` 文件。
个人猜想应该是在复制并修改路径时，
`Cytoid` 之后漏了一个斜杠(逃)

**Comment by TigerHix** [comment]
卧槽，我过了八个月才看到。还有这种操作！？

**Comment by TigerHix** [comment]
![image](https://user-images.githubusercontent.com/3406505/42410512-6975cd60-821d-11e8-89df-e8ab03a1fbb0.png)

我还真写了这个bug..

干...

**Comment by TigerHix** [comment]
Fixed in 1.5.
