### ISSUE TITLE
Rendering notes at the top/bottom of a screen 对于顶天立地note的渲染

### ISSUE THREAD

**Issue by PretTy-Fish** [TigerHix/Cytoid#66]
Some notes at the top or the bottom might be rendered at the opposite side of the screen. It is understandable that the color might be wrong but the position shouldn't change.
一些顶天立地note可能会被渲染在屏幕的对面。颜色很难被确定是可以理解的，但是位置渲染错误是个问题。

Related chart: bombman-deadsoul
相关谱面：bombman-deadsoul

**Comment by TigerHix** [comment]
1.5 已解决。
