### ISSUE TITLE
question about level importing

### ISSUE THREAD

**Issue by LemonZesty** [TigerHix/Cytoid#68]
hello! I'm not sure if this is the right place to ask, but how do you import levels on iOS?
I can only find information on how to import on android.

**Comment by TigerHix** [comment]
Sorry this took ages to reply, but for future reference: on a computer, simply drag-and-drop .cytoidlevel files into Cytoid in the iTunes File Sharing. Or better, download .cytoidlevels on your phone and open them directly.

**Comment by KingNexu** [comment]
i cant open the file directly
