### ISSUE TITLE
Problems with the synchronization of song and notes

### ISSUE THREAD

**Issue by Psypherical** [TigerHix/Cytoid#73]
I have been having issues with the synchronization of the notes to the song while playing all of my maps, in which the song starts considerably later than when the first note appears. This issue is independent of the variable song delay that can be set by the user in the Options panel as changing that value does not solve this issue, no matter how much delay is set.

Best regards,
Psypherical

If it contributes to the troubleshooting process, I own a Google Nexus 6 with 32 gigabytes of storage running LineageOS 14.1.

**Comment by TigerHix** [comment]
Have you ticked the "Override" option? Also, the issue you described seems like a pre-1.3 issue which is fixed in 1.3.1.

**Comment by Psypherical** [comment]
The problem can be reproduced with the Override option checked, and I have verified that my version of Cytoid is 1.3.1. Additionally, there seems to be a bit of lag at the beginning of each song before the problem occurs. Could it potentially be due to the triggers being offset during preload?

**Comment by TigerHix** [comment]
Very weird. Setting the offset to something ridiculous (10.0s for example) doesn't affect the gameplay at all?

**Comment by Psypherical** [comment]
An offset of 10 does not seem to affect gameplay, but setting it to 10.1 seems to solve the problem, oddly enough.

**Comment by Psypherical** [comment]
Well, the solution seems to solve the offset problem for all songs in my library.

Thank you very much for the help!

Sincerely,
Psypherical

**Comment by TigerHix** [comment]
I've reproduced your problem and fixed it in 1.4. The update will be live on Play Store later today!
