### ISSUE TITLE
About translation and other problems 翻译和其他问题

### ISSUE THREAD

**Issue by zcfqq2** [TigerHix/Cytoid#76]
Thought there's not so much text now but... It's always better to provide a loclization file like osu.
Json may be a good choice,for it's easy to be used in the game and fixed,
虽说现在文本量不大，但是设置里面的一些设定还有未来可能新加入的功能也许还是需要提供本地化文本支持才能让更多新人入坑。或许可以采用json文件作为本地化文件，这样修改、引入程序以及各国玩家制作翻译文本都会很方便。

Another problem is about the judgement.It's a bit weird,not so smoo as that in cytus...I think it may be that it's a bit delayed and the judgement area for chains is too small and it's always a little difficult to hit the laste note of a chain? 
还有就是判定的问题。。总觉得有点涩，尤其是锁链没有cytus原版那么顺滑，有的时候觉得稍微有点延迟，还有就是锁链最后一个note经常点不到就很气。所以也许可以适当增大锁链的判定区域，也许会让手感顺滑一点。

Finally I think there might be a built-in online chatting room...I know it's quite difficult to realize but,after all, a little wish.
最后希望可以加入一个在线聊天室。。。当然实现这点很难所以也只是我本人的一点小心愿了。。

希望cytoid能越做越好，给所有的cytoid玩家带来快乐！
Long may Cytoid shine!

**Comment by TigerHix** [comment]
真是个老issue了... 趁没到2019来回应一下。

多语言支持已经计划下个大版本推出了，虽然会用比较暴力的方式实现。

判定的话，目前你玩到的这个判定已经是迭代过很多个版本，被各路大佬鞭策过的判定了。难度上来说比 Cytus 2 要简单许多，网上手机平板的手元也非常多，所以暂时不会再更改了。这其实是个习惯问题啦。

在线聊天室目前不考虑，主要是玩家基数不够。

嗯，希望明年 Cytoid 能变得更好吧。
