### ISSUE TITLE
HTTP 400 - Generic/unknown HTTP error on login attempt

### ISSUE THREAD

**Issue by tcyrus** [TigerHix/Cytoid#78]
![screenshot_20181230-165635](https://user-images.githubusercontent.com/4201229/50551784-acf47980-0c54-11e9-96c3-c24d973115de.png)

**Comment by TigerHix** [comment]
Hi there,

The Cytoid servers are unstable these days. Try to log in with a VPN or
just simply retry a few times.

We would probably migrate to a better infrastructure next year...
